[project]
name = "gran"
version = "0.1.0"
description = "Graph Recurrent Attention Networks for Efficient Graph Generation (NeurIPS 2019)"
requires-python = ">=3.10"
dependencies = [
    "networkx==2.8.8",
    "pyemd==0.5.1",
    "tqdm",
    "tensorboardX",
    "scipy==1.10.1",
    "pyyaml",
    "easydict",
    "matplotlib",
    "opencv-python",
    "shapely",
    "scikit-image",
]

[project.optional-dependencies]
cu118 = [
    "torch==2.0.1",
]
