"""Rule predicates and constants for procedural floor-plan generation.

Constants are loaded from priors.json (generated by mine_priors.py from
msd_wall_v6). Predicates are pure functions: input geometry + room metadata,
output bool / float score. The generator imports these to (a) validate
candidate layouts and (b) score them during local search.

See docs/procedural_rules.md for the rule list and rationale.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Iterable

import networkx as nx
from shapely.geometry import Polygon

ROOM_NAMES = (
    "Bedroom", "Livingroom", "Kitchen", "Dining", "Corridor",
    "Stairs", "Storeroom", "Bathroom", "Balcony",
)
ACCESS_KINDS = frozenset({"door", "passage", "entrance"})
WALL_KIND = "wall"

PRIORS_PATH = Path(__file__).resolve().parent / "priors.json"


@lru_cache(maxsize=1)
def load_priors() -> dict:
    return json.loads(PRIORS_PATH.read_text())


def area_band(room_type: str, band: tuple[int, int] = (10, 90)) -> tuple[float, float]:
    """[p_lo, p_hi] m² for the given room type. R3."""
    rp = load_priors()["room_priors"][room_type]["area_m2"]
    return rp[f"p{band[0]}"], rp[f"p{band[1]}"]


def area_target(room_type: str) -> float:
    """Soft target (p50) m². R3."""
    return load_priors()["room_priors"][room_type]["area_m2"]["p50"]


def is_predominantly_rectangular(room_type: str, threshold: float = 0.40) -> bool:
    """Whether the type's rect_fraction exceeds threshold. R8."""
    return load_priors()["room_priors"][room_type]["rect_fraction"] >= threshold


# ---- R1: backbone identification ------------------------------------------------

def identify_hub_nodes(graph: nx.Graph, room_type_attr: str = "room_type") -> list[int]:
    """Return Corridor node IDs in `graph`. R1.

    `room_type_attr` may be either the int index (raw MSD) or the string name.
    """
    hubs = []
    for n, d in graph.nodes(data=True):
        t = d.get(room_type_attr)
        if isinstance(t, int):
            t = ROOM_NAMES[t]
        if t == "Corridor":
            hubs.append(n)
    return hubs


# ---- R2: leaf attachment feasibility -------------------------------------------

LEAF_ATTACH_PARENTS = {
    "Bedroom":    ("Corridor",),
    "Bathroom":   ("Corridor",),
    "Storeroom":  ("Corridor", "Bedroom"),
    "Stairs":     ("Corridor",),
    "Kitchen":    ("Corridor", "Livingroom"),
    "Dining":     ("Corridor", "Livingroom", "Kitchen"),
    "Balcony":    ("Livingroom", "Bedroom"),
    "Livingroom": ("Corridor",),
    # Corridor itself attaches via R1 backbone, not as a leaf
}


def valid_leaf_parents(leaf_type: str) -> tuple[str, ...]:
    return LEAF_ATTACH_PARENTS.get(leaf_type, ())


# ---- R3: area band check ------------------------------------------------------

def area_in_band(poly: Polygon, room_type: str) -> bool:
    lo, hi = area_band(room_type)
    return lo <= poly.area <= hi


# ---- R4: Livingroom is largest -----------------------------------------------

def livingroom_is_largest(rooms: dict[int, tuple[Polygon, str]]) -> bool:
    """rooms: node_id -> (polygon, type_name). R4."""
    by_type = {}
    for poly, t in rooms.values():
        by_type.setdefault(t, []).append(poly.area)
    if "Livingroom" not in by_type:
        return True  # nothing to violate
    living_max = max(by_type["Livingroom"])
    others_max = max((a for t, areas in by_type.items() if t != "Livingroom" for a in areas), default=0)
    return living_max >= others_max


# ---- R5 / R7: exterior wall requirement --------------------------------------

EXTERIOR_REQUIRED = frozenset({"Bedroom", "Livingroom", "Balcony", "Kitchen"})


def shares_edge_with_boundary(poly: Polygon, boundary: Polygon, eps: float = 0.05) -> bool:
    """Does any edge of `poly` lie on `boundary`'s perimeter?"""
    inter = poly.boundary.intersection(boundary.boundary.buffer(eps))
    return hasattr(inter, "length") and inter.length > eps


def has_required_exterior(poly: Polygon, room_type: str, boundary: Polygon) -> bool:
    """R5 (Bedroom) + R7 (Balcony) + soft window requirements."""
    if room_type not in EXTERIOR_REQUIRED:
        return True
    return shares_edge_with_boundary(poly, boundary)


# ---- R7: balcony parent check -------------------------------------------------

def balcony_has_valid_parent(node: int, graph: nx.Graph,
                              room_types: dict[int, str]) -> bool:
    if room_types.get(node) != "Balcony":
        return True
    parents = LEAF_ATTACH_PARENTS["Balcony"]
    for nbr in graph.neighbors(node):
        if room_types.get(nbr) in parents:
            return True
    return False


# ---- R9: wet-room clustering score -------------------------------------------

WET_ROOM_PAIRS = (
    ("Bathroom", "Bathroom"),
    ("Bathroom", "Kitchen"),
)


def wet_room_cluster_score(adjacency_pairs: Iterable[tuple[str, str]]) -> float:
    """Soft score: +1 per realised wet-room adjacency (Bathroom-Bathroom or
    Bathroom-Kitchen). Higher is better. R9.
    """
    score = 0.0
    for a, b in adjacency_pairs:
        pair = tuple(sorted((a, b)))
        if pair in {tuple(sorted(p)) for p in WET_ROOM_PAIRS}:
            score += 1.0
    return score


# ---- whole-layout validator ---------------------------------------------------

@dataclass
class ValidationReport:
    """Result of running all hard-rule predicates against a candidate layout."""
    ok: bool
    failures: list[str]


def validate_layout(
    rooms: dict[int, tuple[Polygon, str]],
    boundary: Polygon,
    graph: nx.Graph | None = None,
) -> ValidationReport:
    """Run R3, R4, R5, R7 over the layout.

    R1, R2 are pre-conditions enforced by `identify_hub_nodes` /
    `valid_leaf_parents` upstream — they constrain the graph traversal that
    decides where polygons go in the first place. R6 is a permission, not a
    requirement (no check). R8 is a generation hint, not a validation rule.
    R9 contributes to scoring only.
    """
    failures: list[str] = []

    for n, (poly, t) in rooms.items():
        if not area_in_band(poly, t):
            lo, hi = area_band(t)
            failures.append(f"R3: node {n} ({t}) area {poly.area:.2f} outside [{lo}, {hi}]")
        if not has_required_exterior(poly, t, boundary):
            failures.append(f"R5/R7: node {n} ({t}) needs exterior wall")

    if not livingroom_is_largest(rooms):
        failures.append("R4: Livingroom is not the largest room")

    if graph is not None:
        room_types = {n: t for n, (_, t) in rooms.items()}
        for n in rooms:
            if not balcony_has_valid_parent(n, graph, room_types):
                failures.append(f"R7: Balcony node {n} has no Living/Bedroom neighbour")

    return ValidationReport(ok=not failures, failures=failures)
